development:
  server: "http://fruitcake20.info:9292/faye"
 #server: "http://localhost:9292/faye"
  secret_token: "secret"

test:
  server: "http://fruitcake20.info:9292/faye"
   #server: "http://localhost:9292/faye"
  secret_token: "secret"

production:
  server: "http://fruitcake20.info:9292/faye"
   #server: "http://localhost:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
